{
 "title": "Metrics overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "metric", "label": "Metric", "query": { "query": "metrics(.+)" } },
   { "name": "tag", "label": "Inspect tag", "query": { "query": "label_names()" } }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "timeseries",
   "description": "Number of different metric names",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count (group by (name) (count_over_time((label_replace({job=\"alloy\"}, \"name\", \"$1\", \"__name__\", \"(.+)\")[$__range:]))))",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Series",
   "type": "timeseries",
   "description": "Number of different measurement and tag values combinations",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count ((count_over_time((label_replace({job=\"alloy\"}, \"name\", \"$1\", \"__name__\", \"(.+)\")[$__range:]))))",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Series per metric",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    { "panelId": 24 }
   ]
  },
  {
   "title": "Metrics stored",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Series stored",
   "type": "table",
   "description": "Have in mind that each histogram series is compound from several metrics (max, min, avg, percentile, etc.) depending on agent configuration.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time((label_replace({job=\"alloy\"}, \"name\", \"$1\", \"__name__\", \"(.+)\")[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inspect tags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric tags",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "group without (job,instance,metric_type) (count_over_time(label_replace({__name__=~\"$metric\"}, \"name\", \"$1\", \"__name__\", \"(.+)\")[$__range:]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tag values for tag \"$tag\" on $metric",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "group by ($tag) (count_over_time(label_replace({__name__=~\"$metric\"}, \"name\", \"$1\", \"__name__\", \"(.+)\")[$__range:]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics grouped by $tag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "repeat": "metric",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "avg by ($tag) ($metric)", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}