---
services:
  alloy:
    image: grafana/alloy:v1.14.0
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - 8125:8125/udp
      - 12345:12345
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro

  grafana:
    image: grafana/grafana:12.4
    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Editor"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v3.10.0
    depends_on:
      - alloy
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
