---
scrape_configs:
  - job_name: alloy
    scrape_interval: 5s 
    metrics_path: >-
      /api/v0/component/prometheus.exporter.statsd.statsd/metrics
    static_configs:
      - targets:
        - alloy:12345
